### ISSUE TITLE
opencv-python version in requirements.txt

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/ExplainerLibraries#2]
The ```requirements.txt``` file references package opencv-python version 1.22.4

```
opencv-python==1.22.4
```

Are we sure this is correct ? OpenCV seems to be at release 4.6.x or 3.4.x 

This breaks the creation of the Docker image as ```pip``` is unable to meet this requirement.

**Comment by jesusdarias** [comment]
The version of opencv-python should be 4.6.0.66. Just fixed this in the requirements.txt file.
